"""empty message

Revision ID: 9d4672f07c7c
Revises: 
Create Date: 2019-04-16 12:43:44.169296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d4672f07c7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Review')
    op.drop_table('Receipt')
    op.drop_table('Instock')
    op.drop_table('SignUp')
    op.drop_constraint('account_ibfk_1', 'Account', type_='foreignkey')
    op.create_foreign_key(None, 'Account', 'User', ['uid'], ['uid'])
    op.alter_column('Buy', 'branch_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('buy_ibfk_2', 'Buy', type_='foreignkey')
    op.drop_constraint('buy_ibfk_1', 'Buy', type_='foreignkey')
    op.drop_constraint('buy_ibfk_3', 'Buy', type_='foreignkey')
    op.create_foreign_key(None, 'Buy', 'Customer', ['cid'], ['cid'])
    op.create_foreign_key(None, 'Buy', 'Item', ['iid'], ['iid'])
    op.create_foreign_key(None, 'Buy', 'Branch', ['branch_id'], ['branch_id'])
    op.drop_constraint('located_at_ibfk_2', 'Located_At', type_='foreignkey')
    op.drop_constraint('located_at_ibfk_1', 'Located_At', type_='foreignkey')
    op.create_foreign_key(None, 'Located_At', 'Branch', ['branch_id'], ['branch_id'])
    op.create_foreign_key(None, 'Located_At', 'Item', ['iid'], ['iid'])
    op.alter_column('User', 'uname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'uname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_constraint(None, 'Located_At', type_='foreignkey')
    op.drop_constraint(None, 'Located_At', type_='foreignkey')
    op.create_foreign_key('located_at_ibfk_1', 'Located_At', 'item', ['iid'], ['iid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('located_at_ibfk_2', 'Located_At', 'branch', ['branch_id'], ['branch_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Buy', type_='foreignkey')
    op.drop_constraint(None, 'Buy', type_='foreignkey')
    op.drop_constraint(None, 'Buy', type_='foreignkey')
    op.create_foreign_key('buy_ibfk_3', 'Buy', 'item', ['iid'], ['iid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('buy_ibfk_1', 'Buy', 'branch', ['branch_id'], ['branch_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('buy_ibfk_2', 'Buy', 'customer', ['cid'], ['cid'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('Buy', 'branch_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'Account', type_='foreignkey')
    op.create_foreign_key('account_ibfk_1', 'Account', 'user', ['uid'], ['uid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('SignUp',
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('s_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['account.aid'], name='signup_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='signup_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cid', 'aid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Instock',
    sa.Column('iid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('wid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['iid'], ['item.iid'], name='instock_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wid'], ['warehouse.wid'], name='instock_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('iid', 'wid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Receipt',
    sa.Column('rid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('iid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tracknum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['account.aid'], name='receipt_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.branch_id'], name='receipt_ibfk_4', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='receipt_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iid'], ['item.iid'], name='receipt_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rid', 'cid', 'aid', 'iid', 'branch_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Review',
    sa.Column('reviewid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('iid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('review', mysql.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['account.aid'], name='review_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cid'], ['customer.cid'], name='review_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['iid'], ['item.iid'], name='review_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reviewid', 'aid', 'cid', 'iid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
